runtime: java11
entrypoint: java EUClinicalTrialApplication.java
#handlers:
#  - url: /
#    static_files: www/index.html
#    upload: www/index.html
#  - url: /(.*)
#    static_files: www/\1
#    upload: www/(.*)
manual_scaling:
  instances: 1
